### ISSUE TITLE
TypeError on Craft 3.1.19

### ISSUE THREAD

**Issue by bfopma** [ttempleton/craft-nocache#10]
### Description
After upgrading to Craft 3.1.19 from an earlier 3.1 release, I receive the following error related to No-Cache:

`Argument 1 passed to __NoCacheTemplate_ZE9TbMSaN1OaMzFMumUHIwPo::__construct() must be an instance of Environment, instance of craft\web\twig\Environment given, called in /app/vendor/ttempleton/craft-nocache/src/Service.php on line 112`

I am guessing that this is related to the recent Twig 2.7.x changes.

Any help or direction is much appreciated!

### Additional information
- No-Cache version: 2.0.0
- Craft CMS version: 3.1.19
- PHP version: 7.2

**Comment by ttempleton** [comment]
Thanks for reporting, @bfopma!  This has now been fixed in No-Cache 2.0.1.

**Comment by bfopma** [comment]
Thank you, @ttempleton !
