### ISSUE TITLE
Project config migrate "Calling unknown method: craft\console\Request::getToken()"

### ISSUE THREAD

**Issue by Coysh** [ttempleton/craft-nocache#11]
### Description
Installing the plugin locally, then using project config to sync to live production fails:

`./craft project-config/sync
Installing plugin "nocache" ... error: Calling unknown method: craft\console\Request::getToken()
Aborting config sync`

**Comment by Coysh** [comment]
Just need to change line 88 of Service.php to:
`return $generalConfig->enableTemplateCaching && !$request->getIsLivePreview() && !$request->getIsConsoleRequest() && !$request->getToken();`

**Comment by ttempleton** [comment]
Thanks @Coysh!
