### ISSUE TITLE
breaking change with Craft 2.7.7+

### ISSUE THREAD

**Issue by nicklanehq** [ttempleton/craft-nocache#13]
### Description
We've updated a Craft 2 site from 2.7.6 -> 2.7.7 (and above) and it seems to be introducing breaking changes with the nocache plugin. It's giving us the following error anywhere we use this plugin within the Twig templates. 

We noticed starting in Craft 2.7.7 that Twig was updated to 1.38.4. Based on the error in the screenshot attached, we believe that may be the issue.

### Steps to reproduce
1. Update to Craft 2.7.7 or later
2. Attempt to open any page that uses {% nocache % } tags.
3. Receive the following error:
<img width="358" alt="Screen Shot 2019-04-29 at 2 25 20 PM" src="https://user-images.githubusercontent.com/155191/56921951-b0760100-6a8c-11e9-80ab-01471719a4bd.png">

### Additional information
- No-Cache version: 1.0.3
- Craft CMS version: 2.7.7
- PHP version: tested on 5.6,7.0,7.1, and 7.2.x

**Comment by ttempleton** [comment]
Thanks @nicklanehq!  This has now been fixed.  No-Cache for Craft 2 is unlikely to have another official release at this stage, but you can grab the fix from the [`craft-2`](https://github.com/ttempleton/craft-nocache/tree/craft-2) branch (specifically, the [`nocache/twigextensions/NoCache_Node_Module.php`](https://raw.githubusercontent.com/ttempleton/craft-nocache/craft-2/nocache/twigextensions/NoCache_Node_Module.php) file).
