### ISSUE TITLE
Entry does not exist when in between no cache tags

### ISSUE THREAD

**Issue by kaspar-allenbach** [ttempleton/craft-nocache#16]
### Description

In my template: `{{ entry.url }}` outputs the url.

If I write:
```
{% nocache %}
  {{ entry.url }}
{% endnocache %}
```
I get

> Variable "entry" does not exist in "_pages/index" at line 16.

### Steps to reproduce
1. install no cache
2. add no cache tag
3. add something in between the tags

### Additional information
- No-Cache version: 1.0.4
- Craft CMS version: 3.2.3
- PHP version: 7.2.14

**Comment by kaspar-allenbach** [comment]
**OOooohhh**. I get it now. 💡

The entire `{% nocache %}` tag is scoped.
So I have to call everything again within the no cache tag:

**Old:**
```

{% nocache %}
  {% if craft.app.request.getParam('form') != 'success' %}
    {% include "_organisms/bookingForm" %}
  {% else %}
    {{ macro.richText(entry.textSuccess) }}
  {% endif %}
{% endnocache %}
```

**New:**

```
 {% nocache %}
  {% set entry = craft.entries.section('booking').one() %}
  {% import '_incl/docMacros' as macro %}

  {% if craft.app.request.getParam('form') != 'success' %}
    {% include "_organisms/bookingForm" %}
  {% else %}
    {{ macro.richText(entry.textSuccess) }}
  {% endif %}

{% endnocache %}
```

**Comment by kaspar-allenbach** [comment]
or even nicer: 

```
{% nocache with{ entry : entry } %}
   {% import '_incl/docMacros' as macro %}
   {# yadayadayada #}
{% endnocache %}
```

I thought `entry` was a global variable as well.

**Comment by ttempleton** [comment]
@kaspar-allenbach The `entry` isn't a global variable because Craft only sets it to the specific entry required for the page you're viewing, or doesn't set it at all if you're not accessing an entry's page; whereas a global variable like `craft` or `currentUser` will always exist (even if `currentUser` is set to `null` if you're not logged in).
