### ISSUE TITLE
Things Inside of nocache becomes cached.

### ISSUE THREAD

**Issue by wedot** [ttempleton/craft-nocache#17]
### Description
I have the problem that things inside the nocache tag becomes cached. 
It's a onepager, every section is a entry and inside of that i have a neo field.

### Additional information
- No-Cache version: 2.0.4
- Craft CMS version: 3.2.7
- PHP version: 7.1

The Code
```
{% cache globally using key "home-" ~ craft.app.request.pathInfo %}
{%- minify -%}

	{% for entry in entry.siteSection.all() %}
	    <section id="{{ entry.navTitle | kebab }}">
			
			{% if entry.bodyMain is defined and entry.bodyMain | length %}
				{% for block in entry.bodyMain.all() %}
					{% switch block.type.handle %}
			
						{% case 'callTeam' %}	
							
							{% nocache %}
								{% set team = craft.entries.section('team').order('RAND()').all() %}
							
								{% for entry in team %}
									{% switch entry.type %}
										{% case 'team' %}
											Code
									    
									    {% case 'job' %}
									    	Code
									    	
									    {% case 'default' %}
									    
								    {% endswitch %}
								{% endfor %}
							{% endnocache %}

							
					{% endswitch %}
				{% endfor %}
			{% endif %}
			
	    </section>
	{% endfor %}
	
{%- endminify -%}
{% endcache %}
```

**Comment by ttempleton** [comment]
Hi @wedot,

I'm having trouble reproducing this, sorry...  To clarify, is the issue that the order of
```twig
craft.entries.section('team').order('RAND()').all()
```
is always the same?  If so, does it work properly if you remove the `cache` and `nocache` tags?

**Comment by wedot** [comment]
I have found the problem. It don't was your plugin rather then the file caching from my hoster. I don't know that the hoster uses a file caching over the cms caching...

Verything is fine now. thank you for your support :)

**Comment by ttempleton** [comment]
No worries @wedot; good to hear that it's all fine now!
