### ISSUE TITLE
Uncaught Type error

### ISSUE THREAD

**Issue by extensibleseth** [ttempleton/craft-nocache#19]
### Description
Fatal error: Uncaught TypeError: Argument 1 passed to __NoCacheTemplate_cmEum55xsrZjI4i7Hc2xwioM::__construct() must be an instance of Environment, instance of Craft\TwigEnvironment given

### Steps to reproduce
1. Add {% nocache %}text here{% endnocache %} to the template and load the page.

### Additional information
- No-Cache version: 1.0.3
- Craft CMS version: 2.8.0.1
- PHP version: 7.2.24

Also using HTML Cache 1.0.4.1

**Comment by ttempleton** [comment]
Hi @extensibleseth,

This seems to be the same issue as #13; replacing the old `nocache/twigextensions/NoCache_Node_Module.php` with [the updated version](https://raw.githubusercontent.com/ttempleton/craft-nocache/craft-2/nocache/twigextensions/NoCache_Node_Module.php) from the [`craft-2`](https://github.com/ttempleton/craft-nocache/tree/craft-2) branch should fix the error.  There won't be an official release with this fix, for reasons that are explained in #18 (though I'll still maintain the `craft-2` branch in case of compatibility issues with any future Craft 2 releases).
