### ISSUE TITLE
Adding parameter ?token=[any], nocache returns the cache token ID

### ISSUE THREAD

**Issue by jon-collette** [ttempleton/craft-nocache#26]
### Description
When viewing a page that uses the nocache plugin, user can add a invalid token to the URL to change the output chunk to a number string.

### Steps to reproduce
1. View a page that uses the nocache plugin but does not have valid `x-craft-preview` and `token`
2. Update the URL to include the parameter `token` set to anything (e.g., "token=1"). For instance, www.example.com has a news feed with nocache. Update url to www.example.com?token=test
4. Nocache chunk will be replaced with ID or file name matching /craftcms/storage/runtime/compiled_templates/nocache

### Additional information
- No-Cache version: 3.0.0
- Craft CMS version: Craft Pro 4.5.10
- PHP version: 8.0.24

**Comment by jon-collette** [comment]
If this is intentional, would be ideal to update in the docs and/or change to devmode only.

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 3.0.1.
