### ISSUE TITLE
PHP notice on logout from frontend

### ISSUE THREAD

**Issue by klick** [ttempleton/craft-nocache#5]
Users get logged out (path: domain.com/logout) but are being presented with a PHP notice:

`Notice: ob_clean(): failed to delete buffer of zlib output compression (1) in /var/www/virtual/user/craft/app/framework/base/CErrorHandler.php on line 112`

in 

```
ob_get_clean(): failed to discard buffer of zlib output compression (1)

/var/www/virtual/user/craft/plugins/nocache/NoCachePlugin.php(101)

089         // 1. Only enable the plugin's functionality if template caching is enabled
090         // 2. Watch for `nocache` blocks only if it's a site request
091         if(craft()->noCache->isCacheEnabled() && craft()->request->isSiteRequest())
092         {
093             // Working directory may change during `register_shutdown_function`, so let's deal with that by caching the
094             // current working directory to a constant
095             define('NOCACHEPLUGIN_CWD', getcwd());
096 
097             // Capture the raw request output right before it's sent to the requester
098             register_shutdown_function(function()
099             {
100                 $devMode = craft()->config->get('devMode');
101                 $output = ob_get_clean();

(…)

```

Happens in devMode, did not test in production.

**Comment by ttempleton** [comment]
I've reproduced the notice with Craft 2.  That said, based on my testing, it seems that Craft 2 generally doesn't like `ob_get_clean()` within `register_shutdown_function()` on user logout when zlib output compression is enabled (I uninstalled No-Cache and installed a quick test plugin that had the sole purpose of using `ob_get_clean()` within `register_shutdown_function()`).  No-Cache for Craft 2 relies on that setup to provide its functionality, so unfortunately there's nothing I can really do about it.  The only recommendation I can make is to set `zlib.output_compression = Off` in your `php.ini`.

As a side note, No-Cache works in a different way with Craft 3 (making use of a new Craft-provided `afterRenderPageTemplate` event), so it's not affected by this.
