### ISSUE TITLE
Pass macros into nocache

### ISSUE THREAD

**Issue by kaspar-allenbach** [ttempleton/craft-nocache#7]
How would I have to write the nocache tag when using a Macro?

```
{% nocache %}
  {% for asset in header.headerBild.order('RAND()').limit('1') %}
    {{ docMacro.headerImage(asset) }}
  {% endfor %}
{% endnocache %}
```

I just imported the macro file again:
But is there another sollution like `{ with: docMacros }` or something?

```
{% nocache %}
  {% import '_incl/docMacros' as docMacro %}
  {% for asset in header.headerBild.order('RAND()').limit('1') %}
    {{ docMacro.headerImage(asset) }}
  {% endfor %}
{% endnocache %}

```

**Comment by ttempleton** [comment]
The Craft 2 version of No-Cache does allow passing a macro variable declaration; something like...
```twig
{% nocache with {docMacro: docMacro} %}
```
...would work.  I think it'd be better to just re-import what you need, though.

With the Craft 3 version, though, any macros to be used within a `nocache` block must be (re-)imported within the block.
