### ISSUE TITLE
nocache for Craft 3

### ISSUE THREAD

**Issue by tombauer** [ttempleton/craft-nocache#9]
nocache is a really helpful plugin to get more flexibility with caching in Craft. Are there any plans to create a version for Craft 3?

**Comment by ttempleton** [comment]
Hi @tombauer,

A few months ago, with @benjamminf's permission, I ported No-Cache to Craft 3.  Unfortunately, it's yet to see a release on the Craft Plugin Store, which will hopefully be sorted out before too long, but if you (or anyone else) are interested in using No-Cache for Craft 3 now, you can find it here: https://github.com/ttempleton/craft-nocache/tree/craft-3

If anyone using it has any problems to report, I'm happy to address them within this issue.

**Comment by ttempleton** [comment]
No-Cache has now been released for Craft 3 on the Plugin Store.

**Comment by tombauer** [comment]
Perfect, Thanks for the Info :-).
